### ISSUE TITLE
Koodikatselmointi (vertaisarvio 1)

### ISSUE THREAD

**Issue by mikkokotola** [tnatcshlsnki/tiralabra2017#2]
__Vertaisarviointi 1__
HY Tktl / Tiralabra / joulu 2017
Arvioitava: https://github.com/tnatcshlsnki/tiralabra2017
Arvioija: Mikko Kotola
Repo kloonattu: 6.1.2017 klo 17.10

__Hyvää__

* Työ on selvästi edennyt aikataulussa

* Molemmat suunnitellut hakualgoritmit on jo toteutettu

* Pakkaus- ja luokkarakenne on selkeä ja hyvä

* Koodi on hyvin luettavaa (ks. myös alla oleva ehdotus muuttujien nimeämisestä) 

__Kehittämisehdotuksia__

* Yksikkötestaus Junitilla: ConsoleUITest.java testaa tällä hetkellä lähinnä kartan validointia ja validoinnin yhteistyötä käyttöliittymän kassa (ja on sellaisena ehkä pikemminkin toiminnon testi kuin luokan yksikkötesti). Voisi ehkä kirjoittaa yksinkertaisempia yksikkötestejä - tosin tuota UI:ta nyt ei oikeastaan tarvitse yksikkötestata. Myös hakualgoritmien testit ovat tällaisia yhteistyötä testaavia testejä. Varsinaisia yksikkötestejä olisi hyvä saada noille ydinluokille (.types-pakkauksessa) Edge, Graph, Map, Pair. Myös tällaisia laajempaa toimintaa testaavia testejä toki tarvitaan.

* Map.makeMap on hyvin pitkä metodi - tähän olet merkannutkin todo-listalle refaktoroinin utilsiin. Kannattaa varmasti pilkkoa pienemmiksi. Yksi tapa muodostaa olisi käyttää kaikille solmuille vain yhtä ja samaa metodia addEdges(vertice), joka tsekkaisi sisäisesti, onko x- tai y-koordinaatti (tai molemmat) kartan reunalla ja osaisi lisätä sen mukaisesti tarvittavat kaaret.

* Muuttujien nimet ovat tiivistettyjä - ulkopuolisen koodinlukua ja debuggausta voisi auttaa jos muuttujaniminä käyttäisi hieman pidempiä ja kuvaavampia nimiä (esim. Graph.addEdge-metodin rivi p_e = this.E.get(e.u)).

* solve ja getPath kannattaa varmasti eriyttää myös A*:ssa omikse metodeikseen (kuten Dijkstrassa onkin jo tehty) - voisiko jopa jakaa koodia/käyttää yhteistä metodia getPathissa?

__Muut kommentit__

* Määrittelydokumentissa puhutaan minimi-pinosta - kyse lienee minimikeosta

* Jos kyse on suuresta kartasta, Dijkstralle voisi rakentaa solve-metodiin sisään pysäyttäjän, joka pysäyttää haun heti kun haluttu kohdesolmu on löytynyt. Näin voisi tarkastella hakualgoritmien tehokkuutta myös yksittäisen reitin haussa (koko kartan sijaan). Toisaalta jos haluaa toteuttaa ohjelman niin, että koko kartta on ratkaistu tietystä lähtöpisteestä ja sitten voi kysellä etäisyyksiä eri kohdesolmuihin, niin koko kartan ratkaiseminen on tietysti oikea ratkaisu. 

* Astar on oikeastaan aika lähellä Dijkstraa algoritmisesti - se vain laajentaa Dijsktran toimintaa maalin etäisyysestimaatilla ja poimii solmuja keosta huomioiden sekä lähtö- että maalietäisyyden. Yksi mahdollisuus voisikin olla toteuttaa A* perimällä Dijkstran, laajentamalla sitä muutamalla attribuutilla ja korvaamalla sen solmujen compareTo toisella. Mutta tämä toki vain yksi vaihtoehto, myös erilliset toteutukset toimivat varmasti mainiosti.

**Comment by tnatcshlsnki** [comment]
Hei.

Lämpimät kiitokset erinomaisesta palautteesta. En kerennyt toteuttamaan kaikkea tässä ilmi tullutta, mutta olen samaa mieltä kehitysehdotuksista.

Map.makeMapin ehdin kuitenkin hajottaa osiin, tässä suora linkki

https://github.com/tnatcshlsnki/tiralabra2017/blob/master/TiraLabra2017/src/main/java/com/batrachianexcellence/tiralabra2017/types/Map.java

mikäli kiinnostaa vilkaista. Olen itse suht tyytyväinen lopputulokseen, vaikka pieni ääni päässäni kurnuttikin "overengineering, overengineering!" koko ajan. Ja noiden private final inttien pitäisi varmaan olla consteja.

Muuttujien nimien refaktorointi on epävirallisella tehtävälistalla. Paremmat yksikkötestit struct moduulin kamoille saa DLC:nä.

Kiitokset vielä toistamiseen, on helppo parantaa tuotetta kun palaute on harvinaisen selkeää ja pätevää.
